version: '3.8'

services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: web
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    restart: unless-stopped
#
#  postgres:
#    image: postgres:12.0-alpine
#    container_name: db
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_PORT: ${KC_DB_URL_PORT}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_ADMIN: ${KC_ADMIN}
      KC_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    ports:
      - "8080:8080"

#volumes:
#  postgres_data:
